patch puzzle mutation
lumy/EternityII pull request #30
Opened 2017-02-04 15:44 UTC by lumy

forgot to do a good comment link to the issue. sorry. #25

2017-02-04 18:58 UTC, Grenadingue requested changes

2017-02-04 18:58 UTC, Grenadingue commented on puzzle.py
> +        if (rand <= config.mutate_inpd):
`rand` has range `[0, 100]`, but `config.mutate_inpd` from [`config.py`](https://github.com/lumy/EternityII/blob/%2325_patch_mutation/config.py#L28) has range `[0.0, 1.0]`

2017-02-04 18:58 UTC, Grenadingue commented on puzzle.py
> +          # operation == 3 both if work, operation == 2 only the first one and for operation == 1 only the second one.
It took for me quite a lot of time to understand what means this comment. I needed to understand the function to understand the comment. Comment which is supposed to explain the function. Do you mind if we replace the comment by the following ?
```python
# operation == 1 mutate rotation # operation == 2 mutate position # operation == 3 mutate both
`

2017-02-04 19:01 UTC, lumy commented on puzzle.py
> +          # operation == 3 both if work, operation == 2 only the first one and for operation == 1 only the second one.
No probleme. doing that asap

2017-02-05 01:11 UTC, lumy commented
Done. need new review

2017-02-05 13:13 UTC, Grenadingue approved these changes

2017-02-05 13:17 UTC, AdriVig approved these changes

2017-02-05 13:28 UTC, merged